---
abstract: 'PDL Interface to the HDF5 Data Format'
author:
  - 'Chris Marshall <chm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  PDL: 2.007
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  PDL: 2.004
dynamic_config: 1
generated_by: 'Chris Marshall, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-IO-HDF5
no_index:
  directory:
    - t
    - inc
provides:
  PDL::IO::HDF5:
    file: hdf5.pd
    version: 0.6501
requires:
  PDL: 2.004
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=PDL-IO-HDF5
  homepage: http://pdl.perl.org/
  license: http://cpansearch.perl.org/src/CHM/PDL-IO-HDF5-0.65/COPYRIGHT
  repository: git://git.code.sf.net/p/pdl/pdl-io-hdf5
version: 0.6501
